name: Build & Deploy

on:
  push:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to GitHub Pages'
        type: boolean
        required: false
        default: true

jobs:
  build-deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    strategy:
        matrix:
          node-version: ['20.x']
    steps:
        - name: Set up Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: yarn
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install dependencies
          run: yarn install
        - name: Build
          run: yarn build
        - name: Upload Pages artifact
          uses: actions/upload-pages-artifact@v3
          with:
            path: ./build
        - name: Deploy to GitHub Pages
          if: ${{ inputs.deploy }}
          uses: actions/deploy-pages@v4
